apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-project-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-project-web
  template:
    metadata:
      labels:
        app: php-project-web
    spec:
      containers:
        - name: web
          image: baretsky24/php-project-web
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: php-project-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort